#!/bin/bash

if [ -z "$1" ]; then
    ENVIRONMENT="dev"
    echo "No environment specified, defaulting to: dev"
else
    ENVIRONMENT=$1
fi

# Define all environment variables (set defaults for empty values)
KEY_VAULT_NAME=kv-arata-ai-${ENVIRONMENT}
URL_SCHEME=http
DATABASE_K8S_DOMAIN=localhost:8000
FILE_K8S_DOMAIN=localhost:8002
TOKEN_BROKER_K8S_DOMAIN=localhost:8001
MARKDOWN_K8S_DOMAIN=localhost:8007
VECTORDB_K8S_DOMAIN=localhost:8003
TENANT_REGISTRY_K8S_DOMAIN=localhost:8009
TEMPORAL_ENDPOINT="localhost:7233"
TEMPORAL_API_KEY="${TEMPORAL_API_KEY:-}"
TEMPORAL_TLS="${TEMPORAL_TLS:-False}"
TEMPORAL_NAMESPACE="${TEMPORAL_NAMESPACE:-default}"
LAW_WORKSPACE_ID="${LAW_WORKSPACE_ID:-}"
LAW_CONNECTION_STRING_SECRET="${LAW_CONNECTION_STRING_SECRET:-}"
GEMINI_API_KEY="$(az keyvault secret show --name "gemini-api-key" --vault-name $KEY_VAULT_NAME --query "value" -o tsv)"
VOYAGE_API_KEY="${VOYAGE_API_KEY:-}"
DOCUMENT_INTELLIGENCE_ENDPOINT="${DOCUMENT_INTELLIGENCE_ENDPOINT:-}"
DOCUMENT_INTELLIGENCE_API_KEY="${DOCUMENT_INTELLIGENCE_API_KEY:-}"
SLACK_WORKFLOW_FAILURE_WEBHOOK_URL="${SLACK_WORKFLOW_FAILURE_WEBHOOK_URL:-}"

# Get Azure credentials from Key Vault
AZURE_TENANT_ID=$(az keyvault secret show --name "entra-tenant-id" --vault-name $KEY_VAULT_NAME --query "value" -o tsv)
AZURE_CLIENT_ID=$(az keyvault secret show --name "agent-email-summarizer-app-id" --vault-name $KEY_VAULT_NAME --query "value" -o tsv)
AZURE_CLIENT_SECRET=$(az keyvault secret show --name "agent-email-summarizer-app-secret" --vault-name $KEY_VAULT_NAME --query "value" -o tsv)

# Create .env file with all variables
cat > .env << EOF
KEY_VAULT_NAME=$KEY_VAULT_NAME
URL_SCHEME=$URL_SCHEME
DATABASE_K8S_DOMAIN=$DATABASE_K8S_DOMAIN
FILE_K8S_DOMAIN=$FILE_K8S_DOMAIN
MARKDOWN_K8S_DOMAIN=$MARKDOWN_K8S_DOMAIN
TOKEN_BROKER_K8S_DOMAIN=$TOKEN_BROKER_K8S_DOMAIN
VECTORDB_K8S_DOMAIN=$VECTORDB_K8S_DOMAIN
TENANT_REGISTRY_K8S_DOMAIN=$TENANT_REGISTRY_K8S_DOMAIN
TEMPORAL_ENDPOINT=$TEMPORAL_ENDPOINT
TEMPORAL_API_KEY=$TEMPORAL_API_KEY
TEMPORAL_TLS=$TEMPORAL_TLS
TEMPORAL_NAMESPACE=$TEMPORAL_NAMESPACE
LAW_WORKSPACE_ID=$LAW_WORKSPACE_ID
LAW_CONNECTION_STRING_SECRET=$LAW_CONNECTION_STRING_SECRET
GEMINI_API_KEY=$GEMINI_API_KEY
VOYAGE_API_KEY=$VOYAGE_API_KEY
DOCUMENT_INTELLIGENCE_ENDPOINT=$DOCUMENT_INTELLIGENCE_ENDPOINT
DOCUMENT_INTELLIGENCE_API_KEY=$DOCUMENT_INTELLIGENCE_API_KEY
SLACK_WORKFLOW_FAILURE_WEBHOOK_URL=$SLACK_WORKFLOW_FAILURE_WEBHOOK_URL
AZURE_TENANT_ID=$AZURE_TENANT_ID
AZURE_CLIENT_ID=$AZURE_CLIENT_ID
AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET
EOF

# Append contents of .local_secrets to .env (removing 'export' keyword)
# This ensures any additional variables from .local_secrets are included
if [ -f .local_secrets ]; then
    sed 's/^export //' .local_secrets >> .env
fi

# Export all variables for current shell session
export KEY_VAULT_NAME
export DATABASE_K8S_DOMAIN
export FILE_K8S_DOMAIN
export TOKEN_BROKER_K8S_DOMAIN
export VECTORDB_K8S_DOMAIN
export MARKDOWN_K8S_DOMAIN
export TENANT_REGISTRY_K8S_DOMAIN
export TEMPORAL_ENDPOINT
export TEMPORAL_API_KEY
export TEMPORAL_TLS
export TEMPORAL_NAMESPACE
export LAW_WORKSPACE_ID
export LAW_CONNECTION_STRING_SECRET
export GEMINI_API_KEY
export VOYAGE_API_KEY
export DOCUMENT_INTELLIGENCE_ENDPOINT
export DOCUMENT_INTELLIGENCE_API_KEY
export SLACK_WORKFLOW_FAILURE_WEBHOOK_URL
export AZURE_TENANT_ID
export AZURE_CLIENT_ID
export AZURE_CLIENT_SECRET
export URL_SCHEME
