{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HealthCheckPolicy
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "email-summarizer-ui.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: {{ .Values.app.name }}
      namespace: {{ .Values.namespace }}
  interval: 10s
  timeout: 3s
  unhealthyThreshold: 3
  healthyThreshold: 1
  http:
    path: {{ .Values.app.path }}
    port: {{ .Values.app.port }}
    host: localhost
{{- end }}
