apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "email-summarizer-ui.labels" . | nindent 4 }}
  {{- if .Values.gateway.enabled }}
  annotations:
    alb.networking.azure.io/alb-endpoint-type: "service"
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "email-summarizer-ui.selectorLabels" . | nindent 4 }}
