
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: document-controller
  annotations:
    helm.sh/resource-policy: keep
  {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}

